datasource_variable: DS_POSTGRES

dashboards:

  - title: "Environment Monitoring (trend)"
    panels:
      - title: "Temperature (°C)"
        table: "temp_humidity"
        chart_type: "timeseries"
        condition: "temp_humidity.temp_c IS NOT NULL"
        groupby: ["log_timestamp", "temp_c"]
        filters: {"temp_humidity": ["log_location"]}
        distinct: 
      - title: "Humidity"
        table: "temp_humidity"
        chart_type: "timeseries"
        condition: "temp_humidity.rel_hum IS NOT NULL"
        groupby: ["log_timestamp", "rel_hum"]
        filters: {"temp_humidity": ["log_location"]}
        distinct: 
      - title: "500nm Particle Count"
        table: "particulate_counts"
        chart_type: "timeseries"
        condition: "particulate_counts.prtcls_per_cubic_m_500nm IS NOT NULL"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_500nm"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "1um Particle Count"
        table: "particulate_counts"
        chart_type: "timeseries"
        condition: "particulate_counts.prtcls_per_cubic_m_1um IS NOT NULL"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_1um"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "5um Particle Count"
        table: "particulate_counts"
        chart_type: "timeseries"
        condition: "particulate_counts.prtcls_per_cubic_m_5um IS NOT NULL"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_5um"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
  
  - title: "Environment Monitoring (current)"
    panels:
      - title: "Temperature (°C) (main_clean_room)"
        table: "temp_humidity"
        chart_type: "gauge"
        condition: "temp_humidity.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '15 MINUTE'"
        groupby: ["temp_c"]
        filters: {}
        distinct: 
      - title: "Humidity (main_clean_room)"
        table: "temp_humidity"
        chart_type: "gauge"
        condition: "temp_humidity.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '15 MINUTE'"
        groupby: ["rel_hum"]
        filters: {}
        distinct: 
      - title: "500nm Particle Count (main_clean_room)"
        table: "particulate_counts"
        chart_type: "gauge"
        condition: "particulate_counts.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '75 MINUTE'"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_500nm"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "1um Particle Count (main_clean_room)"
        table: "particulate_counts"
        chart_type: "gauge"
        condition: "particulate_counts.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '75 MINUTE'"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_1um"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "5um Particle Count (main_clean_room)"
        table: "particulate_counts"
        chart_type: "gauge"
        condition: "particulate_counts.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '75 MINUTE'"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_5um"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 


alert:
  - title: "High Temperature Alert"
    table: "temp_humidity"
    dashboard: "Environment Monitoring (trend)"
    panelID: "1"
    parameter: "temp_c"
    threshold: [18,30]
    logicType: "outside_range"
    duration: "3s"
    interval: "10m"
    summary: "Temperature exceeds 25°C"
    labels: 
        "team": "inspectors"
        "severity": "critical"
        "sensor": "temp"
        "location": "main_clean_room"
      
  - title: "High Humidity Alert"
    table: "temp_humidity"
    dashboard: "Environment Monitoring (trend)"
    panelID: "2"
    parameter: "rel_hum"
    threshold: [30]
    logicType: "lt"
    duration: "3s"
    interval: "10m"
    summary: "Humidity abnormal"
    labels: 
        "team": "inspectors"
        "severity": "critical"
        "sensor": "humidity"
        "location": "main_clean_room"