datasource_variable: DS_POSTGRES

dashboards:

  - title: "Environment Monitoring (trend)"
    panels:
      - title: "Temperature (°C)"
        table: "temp_humidity"
        chart_type: "timeseries"
        condition: "temp_humidity.temp_c IS NOT NULL"
        groupby: ["log_timestamp", "temp_c", "log_location"]
        filters: {"temp_humidity": ["log_location"]}
        distinct: 
      - title: "Humidity"
        table: "temp_humidity"
        chart_type: "timeseries"
        condition: "temp_humidity.rel_hum IS NOT NULL"
        groupby: ["log_timestamp", "rel_hum", "log_location"]
        filters: {"temp_humidity": ["log_location"]}
        distinct: 
      - title: "500nm Particle Count"
        table: "particulate_counts"
        chart_type: "timeseries"
        condition: "particulate_counts.prtcls_per_cubic_m_500nm IS NOT NULL"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_500nm", "log_location"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "1um Particle Count"
        table: "particulate_counts"
        chart_type: "timeseries"
        condition: "particulate_counts.prtcls_per_cubic_m_1um IS NOT NULL"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_1um", "log_location"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "5um Particle Count"
        table: "particulate_counts"
        chart_type: "timeseries"
        condition: "particulate_counts.prtcls_per_cubic_m_5um IS NOT NULL"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_5um", "log_location"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
  
  - title: "Environment Monitoring (current)"
    panels:
      - title: "Temperature (°C) (main_clean_room)"
        table: "temp_humidity"
        chart_type: "gauge"
        condition: "temp_humidity.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '15 MINUTE'"
        groupby: ["temp_c"]
        filters: {}
        distinct: 
      - title: "Humidity (main_clean_room)"
        table: "temp_humidity"
        chart_type: "gauge"
        condition: "temp_humidity.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '15 MINUTE'"
        groupby: ["rel_hum"]
        filters: {}
        distinct: 
      - title: "500nm Particle Count (main_clean_room)"
        table: "particulate_counts"
        chart_type: "gauge"
        condition: "particulate_counts.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '75 MINUTE'"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_500nm"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "1um Particle Count (main_clean_room)"
        table: "particulate_counts"
        chart_type: "gauge"
        condition: "particulate_counts.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '75 MINUTE'"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_1um"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 
      - title: "5um Particle Count (main_clean_room)"
        table: "particulate_counts"
        chart_type: "gauge"
        condition: "particulate_counts.log_location = 'main_clean_room' AND (now() - log_timestamp AT TIME ZONE 'America/New_York') < INTERVAL '75 MINUTE'"
        groupby: ["log_timestamp", "prtcls_per_cubic_m_5um"]
        filters: {"particulate_counts": ["log_location"]}
        distinct: 


alert:
  - title: "Abnormal Temperature Alert"
    table: "temp_humidity"
    dashboard: "Environment Monitoring (trend)"
    panelID: "1"
    parameter: "temp_c"
    threshold: [18,30]
    logicType: "outside_range"
    duration: "3s"
    interval: "10m"
    summary: "Temperature is out of the range of [18˚C, 30˚C]"
    labels: 
        "team": "inspectors"
        "severity": "critical"
        "sensor": "temp"
        "location": "main_clean_room"
      
  - title: "Abnormal Humidity Alert"
    table: "temp_humidity"
    dashboard: "Environment Monitoring (trend)"
    panelID: "2"
    parameter: "rel_hum"
    threshold: [30]
    logicType: "lt"
    duration: "3s"
    interval: "10m"
    summary: "Humidity is less than 30%"
    labels: 
        "team": "inspectors"
        "severity": "critical"
        "sensor": "humidity"
        "location": "main_clean_room"

  - title: "High 500nm Particle Count Alert"
    table: "particulate_counts"
    dashboard: "Environment Monitoring (trend)"
    panelID: "3"
    parameter: "prtcls_per_cubic_m_500nm"
    threshold: [352000]
    logicType: "gt"
    duration: "3s"
    interval: "60m"
    summary: "500nm Particle Count is larger than 352000"
    labels: 
        "team": "inspectors"
        "severity": "critical"
        "sensor": "500nm_particle_count"
        "location": "main_clean_room"

  - title: "High 1um Particle Count Alert"
    table: "particulate_counts"
    dashboard: "Environment Monitoring (trend)"
    panelID: "4"
    parameter: "prtcls_per_cubic_m_1um"
    threshold: [83200]
    logicType: "gt"
    duration: "3s"
    interval: "60m"
    summary: "1um Particle Count is larger than 83200"
    labels: 
        "team": "inspectors"
        "severity": "critical"
        "sensor": "1um_particle_count"
        "location": "main_clean_room"